services:
    minecraft:
        image: itzg/minecraft-server
        container_name: minecraft
        ports:
            - "25565:25565"
        environment:
            EULA: "TRUE"
            TYPE: "PAPER"
            VERSION: "1.21.8"
            MEMORY: "4G"
            ONLINE_MODE: "FALSE"

            SEED: "77086492"
            DIFFICULTY: "hard"
            SPAWN_PROTECTION: "0"

            MOTD: "§c§kd§r§r Adoumaaaa §c§kd§r§r§c §r§dMibounaaaa §r§c§kd§r§r"
            ICON: "https://nats.are-la.me/7qfYVxa.png"

            PLUGINS: |
                https://download.luckperms.net/1624/bukkit/loader/LuckPerms-Bukkit-5.5.36.jar
                https://hangarcdn.papermc.io/plugins/SRTeam/SkinsRestorer/versions/15.10.0/PAPER/SkinsRestorer.jar
                https://hangarcdn.papermc.io/plugins/UNTONE/DiscordWebhookJoinLeave/versions/1.2.2/PAPER/DiscordJoinLeaveMessages-1.2.2-SNAPSHOT.jar
                https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.7.1/PAPER/ViaVersion-5.7.1.jar
                https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/5.7.1/PAPER/ViaBackwards-5.7.1.jar
                https://hangarcdn.papermc.io/plugins/DestenyLP/VeinMiner/versions/2.1/PAPER/VeinMiner-2.1.jar
                https://hangarcdn.papermc.io/plugins/CyntrixAlgorithm/DeathChest/versions/2.2.9/PAPER/deathchest.jar
                https://hangarcdn.papermc.io/plugins/Atri/Waystones/versions/2.1.4-1.21.11/PAPER/waystones-2.1.4-1.21.11.jar

            ENABLE_AUTOPAUSE: "TRUE"
            AUTOPAUSE_TIMEOUT_EST: "300"
            AUTOPAUSE_TIMEOUT_INIT: "600"
            AUTOPAUSE_PERIOD: "10"

            OPS: "Hivie_"

        volumes:
            - ./data:/data
        restart: unless-stopped
